look_up_table = [{'Register': 4999, 'Name': 'Geräte Typ-Code', 'Einheit': '', 'Faktor': 1.0, 'word_count': 1}, 
                 {'Register': 5000, 'Name': 'Installierte Leistung', 'Einheit': 'Kw', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 5002, 'Name': 'Eigene Energienutzung heute (PV & Akku)', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 5003, 'Name': 'Eigene Energienutzung gesamt (PV & Akku)', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 2}, 
                 {'Register': 5007, 'Name': 'Temperatur im Wechselrichter', 'Einheit': '°C', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 5010, 'Name': 'MPPT1 Spannung', 'Einheit': 'V', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 5011, 'Name': 'MPPT1 Strom', 'Einheit': 'A', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 5012, 'Name': 'MPPT2 Spannung', 'Einheit': 'V', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 5013, 'Name': 'MPPT2 Strom', 'Einheit': 'A', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 5016, 'Name': 'PV-Leistung aktuell', 'Einheit': 'W', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 5018, 'Name': 'Spannung Phase A', 'Einheit': 'V', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 5019, 'Name': 'Spannung Phase C', 'Einheit': 'V', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 5020, 'Name': 'Spannung Phase C', 'Einheit': 'V', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 5032, 'Name': 'Blindleistung', 'Einheit': 'VA®', 'Faktor': 0, 'word_count': 2}, 
                 {'Register': 5034, 'Name': 'Leistungsfaktor', 'Einheit': '', 'Faktor': 1.0, 'word_count': 1}, 
                 {'Register': 5035, 'Name': 'Netzfrequenz', 'Einheit': 'Hz', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6226, 'Name': ' Monatlicher PV Energieertrag  Januar', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6227, 'Name': ' Monatlicher PV Energieertrag Februar', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6228, 'Name': ' Monatlicher PV Energieertrag März', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6229, 'Name': ' Monatlicher PV Energieertrag April', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6230, 'Name': ' Monatlicher PV Energieertrag Mai', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6231, 'Name': ' Monatlicher PV Energieertrag Juni', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6232, 'Name': ' Monatlicher PV Energieertrag Juli', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6233, 'Name': ' Monatlicher PV Energieertrag August', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6234, 'Name': ' Monatlicher PV Energieertrag September', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6235, 'Name': ' Monatlicher PV Energieertrag Oktober', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6236, 'Name': ' Monatlicher PV Energieertrag November', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6237, 'Name': ' Monatlicher PV Energieertrag Dezember', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6416, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im Januar', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6417, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im Februar', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6418, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im März', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6419, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im April', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6420, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im Mai', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6421, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im Juni', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6422, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im Juli', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6423, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im August', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6424, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im September', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6425, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im Oktober', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6426, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im November', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6427, 'Name': 'Monatlicher Energieverbrauch von PV-Anlage im Dezember', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6595, 'Name': ' Monatlicher Energieexport aus PV-Anlage Januar', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6596, 'Name': ' Monatlicher Energieexport aus PV-Anlage Februar', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6597, 'Name': ' Monatlicher Energieexport aus PV-Anlage März', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6598, 'Name': ' Monatlicher Energieexport aus PV-Anlage April', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6599, 'Name': ' Monatlicher Energieexport aus PV-Anlage Mai', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6600, 'Name': ' Monatlicher Energieexport aus PV-Anlage Juni', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6601, 'Name': ' Monatlicher Energieexport aus PV-Anlage Juli', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6602, 'Name': ' Monatlicher Energieexport aus PV-Anlage August', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6603, 'Name': ' Monatlicher Energieexport aus PV-Anlage September', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6604, 'Name': ' Monatlicher Energieexport aus PV-Anlage Oktober', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6605, 'Name': ' Monatlicher Energieexport aus PV-Anlage November', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 6606, 'Name': ' Monatlicher Energieexport aus PV-Anlage Dezember', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 12999, 'Name': 'Systemstatus', 'Einheit': '', 'Faktor': 1.0, 'word_count': 1}, 
                 {'Register': 13000, 'Name': 'Betriebsstatus', 'Einheit': '', 'Faktor': 1.0, 'word_count': 1}, 
                 {'Register': 13001, 'Name': 'PV-Stromerzeugung heute', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13002, 'Name': 'PV-Stromerzeugung gesamt', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 2}, 
                 {'Register': 13004, 'Name': 'PV-Einspeise Energie heute', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13005, 'Name': 'PV-Einspeise Energie gesamt', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 2}, 
                 {'Register': 13007, 'Name': 'Wirkleistung gesamt', 'Einheit': 'W', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13009, 'Name': 'Aktuelle Leistung am Übergabepunkt des Versorgungsnetzes', 'Einheit': 'W', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13011, 'Name': 'Energie in Speicher heute', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13012, 'Name': 'Energie in Speicher gesamt', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 2}, 
                 {'Register': 13014, 'Name': 'CO2- Reduzierung', 'Einheit': 'Kg', 'Faktor': 0.1, 'word_count': 2}, 
                 {'Register': 13016, 'Name': 'Direkter Eigenverbrauch aus PV heute', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13017, 'Name': 'Direkter Eigenverbrauch aus PV gesamt', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 2}, 
                 {'Register': 13019, 'Name': 'Batteriespannung', 'Einheit': 'V', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13020, 'Name': 'Batteriestrom', 'Einheit': 'A', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13021, 'Name': 'Batterieladeleistung', 'Einheit': 'W', 'Faktor': 1.0, 'word_count': 1}, 
                 {'Register': 13022, 'Name': 'Batteriekapazität', 'Einheit': '%', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13023, 'Name': 'Gesundheit der Batterie', 'Einheit': '%', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13024, 'Name': 'Batterietemperatur', 'Einheit': '°C', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13025, 'Name': 'Tägliche Entladungsenergie der Batterie', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13026, 'Name': 'Gesamte Entladungsenergie der Batterie', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 2}, 
                 {'Register': 13028, 'Name': 'Heutiger Anteil des Eigenverbrauches', 'Einheit': '%', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13029, 'Name': 'Netzstatus', 'Einheit': '', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13030, 'Name': 'Strom Phase A aktuell', 'Einheit': 'A', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13031, 'Name': 'Strom Phase B aktuell', 'Einheit': 'A', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13032, 'Name': 'Strom Phase C aktuell', 'Einheit': 'A', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13033, 'Name': 'Eigenverbrauch aktuell', 'Einheit': 'W', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13035, 'Name': 'Gekaufte Energie heute', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13036, 'Name': 'Gekaufte Energie gesamt', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13038, 'Name': 'Batterie-Kapazität', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13039, 'Name': 'Batterie-Ladeenergie heute', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13040, 'Name': 'Batterie-Ladeenergie gesamt', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 2}, 
                 {'Register': 13044, 'Name': 'Energie Netzeinspeisung heute', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 1}, 
                 {'Register': 13045, 'Name': 'Energie Netzeinspeisung gesamt', 'Einheit': 'Kwh', 'Faktor': 0.1, 'word_count': 2}, 
                 {'Register': 13049, 'Name': 'Inverter alarm', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13051, 'Name': 'Netzfehler', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13053, 'Name': 'System Fehler 1', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13055, 'Name': 'System Fehler 2', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13057, 'Name': 'Fehler DC-Seitig', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13059, 'Name': 'Permanenter Fehler', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13061, 'Name': 'BDC-side fault', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13063, 'Name': 'BDC-side permanent fault', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13065, 'Name': 'Batterie Fehler', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13067, 'Name': 'Battery Alarm', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13069, 'Name': 'BMS Alarm', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13071, 'Name': 'BMS protection', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2},
                 {'Register': 13073, 'Name': 'BMS fault 1', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13075, 'Name': 'BMS fault 2', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}, 
                 {'Register': 13077, 'Name': 'BMS alarm 2', 'Einheit': '', 'Faktor': 1.0, 'word_count': 2}]